<a href="https://colab.research.google.com/github/atulpatil2228/pwlectures/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## numpy >> numerical python
## 2005 by travis oliphant

In [2]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [9]:
lis=[1,2,3,4,"pwskills",True,1.2]

In [10]:
type(lis)

list

In [11]:
## Numpy stores the data in array
## an array is a container used to store same data type


In [14]:
## why numpy
## computation is faster >> due to array  >> continous memory location
## mathematical computation

In [15]:
l = [1,2,3,4,5]

In [16]:
arr =np.array(l)

In [17]:
arr

array([1, 2, 3, 4, 5])

In [20]:
l = [1,2,3,4,5.1]
arr = np.array(l) ## sores homogenous data

In [21]:
arr

array([1. , 2. , 3. , 4. , 5.1])

In [22]:
l = [1,2,3,4,5.1 ,"atul"]
arr = np.array(l) ## sores homogenous data


In [23]:
arr

array(['1', '2', '3', '4', '5.1', 'atul'], dtype='<U32')

In [24]:
## array stores homogenous data

In [25]:
type(arr)

numpy.ndarray

In [26]:
arr.ndim

1

In [27]:
arr1= np.array([[1,2,3],[4,5,6]])

In [28]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr1.ndim

2

In [34]:
mat =np.matrix([1,2,3,4]) # matrix is specialised arrray , 2 dimensional

In [35]:
mat

matrix([[1, 2, 3, 4]])

In [36]:
type(mat)

numpy.matrix

In [37]:
np.matrix([[[1,2],[3,4],[5,6]]])

ValueError: matrix must be 2-dimensional

In [38]:
## more way to convert array
l= [1,2,3]
np.asarray(l)

array([1, 2, 3])

In [39]:
mat

matrix([[1, 2, 3, 4]])

In [40]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [42]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [44]:
np.asanyarray(mat) ## convert the input to an ndarray, but pass ndarray subclasses through

matrix([[1, 2, 3, 4]])

In [45]:
t = ([1,2,3],[4,5,6]) ## tupple to array

In [46]:
type(t)

tuple

In [47]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
l = [1,2,3,4,5]
arr = np.array(l)

In [51]:
arr

array([1, 2, 3, 4, 5])

In [53]:
arr[0] = 500

In [54]:
arr

array([500,   2,   3,   4,   5])

In [55]:
arr

array([500,   2,   3,   4,   5])

In [56]:
a = arr

In [57]:
a

array([500,   2,   3,   4,   5])

In [58]:
arr[0] = 1000

In [61]:
a ## change is array also led to change in a  >> shallow coppy

array([1000,    2,    3,    4,    5])

In [62]:
a  = arr.copy()

In [63]:
a

array([1000,    2,    3,    4,    5])

In [64]:
arr

array([1000,    2,    3,    4,    5])

In [65]:
arr[0] = 2000

In [66]:
arr

array([2000,    2,    3,    4,    5])

In [67]:
a

array([1000,    2,    3,    4,    5])

In [68]:
## To create an array >> np.array ,np.asarray ,np.asanyarray ,deep copy and shallow copy

In [69]:
## Mutiple ways to generate array

In [72]:
arr1  = np.fromfunction(lambda i,j : i==j,(3,3)) ## construct an array by executing a function over each coordinate

In [73]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [74]:
arr1.ndim

2

In [75]:
arr1.shape # shape of array

(3, 3)

In [77]:
arr1.size # no of elements

9

In [78]:
arr2  = np.fromfunction(lambda i,j : i*j,(3,3))

In [79]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [80]:
for i in range(5):
  print(i)

0
1
2
3
4


In [81]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [83]:
iterable = (i for i in range(5))

In [86]:
np.fromiter(iterable,int) ## Create an new dimensional array from an iterable object

array([], dtype=int64)

In [89]:
np.fromstring('22 23 44' ,sep = '')

<ipython-input-89-01ebd4a00774>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring('22 23 44' ,sep = '')


array([3.20622192e-57])

In [90]:
np.fromstring('22 23 44' ,sep = '')

<ipython-input-90-01ebd4a00774>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring('22 23 44' ,sep = '')


array([3.20622192e-57])

In [91]:
import numpy as np
np.fromstring('22 23 44', sep=' ') ## valus should be numerical


array([22., 23., 44.])

In [99]:
import numpy as np
np.fromstring('22, 23, 44', sep=",")

array([22., 23., 44.])

In [94]:
import numpy as np
np.fromstring('Atul abhi anna ', sep=' ')


<ipython-input-94-de59191e31a5>:2: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Atul abhi anna ', sep=' ')


array([], dtype=float64)

In [100]:
## for string charater  you have to use split
string = 'Atul ,annna, abhi'
string1 = string.split(',')
np.array(string1)

array(['Atul ', 'annna', ' abhi'], dtype='<U5')

In [102]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [104]:
## other methods of numpy >> to generate sequence of nos
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [108]:
np.linspace(1,5,11) ## Return evenly spaced numbers over a specified interval.
## give me 10 numbers between 1 and 5 evenly spaced

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [110]:
np.logspace(1,5,10) ## base is 10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [111]:
np.logspace(1,5,10 ,base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])