<a href="https://colab.research.google.com/github/atulpatil2228/pwlectures/blob/main/numpy_advance1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [4]:
a = np.zeros(5)#Return a new array of given shape and type, filled with zeros.

In [5]:
a.ndim

1

In [6]:
b= np.zeros((3,4))

In [7]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b.ndim

2

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.twos(2)

AttributeError: module 'numpy' has no attribute 'twos'

In [13]:
np.array([[2,2,2] ,[2,2,3]])

array([[2, 2, 2],
       [2, 2, 3]])

In [16]:
arr = np.zeros((3,4))

In [17]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
arr.ndim

2

In [19]:
## 3 dimensional array
np.zeros(1)

array([0.])

In [21]:
np.zeros(2)

array([0., 0.])

In [23]:
np.zeros((2,3)).ndim

2

In [24]:
arr = np.zeros((3,4))
arr.ndim

2

In [25]:
arr = np.zeros((1,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
arr.ndim

3

In [27]:
arr = np.zeros((1,1,3,4))

In [28]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [29]:
arr.ndim

4

In [30]:
arr = np.zeros((1,1,1,3,4))

In [31]:
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [32]:
arr.ndim

5

In [33]:
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [34]:
arr = np.ones((3,4))

In [35]:
arr.ndim

2

In [36]:
arr.shape

(3, 4)

In [37]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [41]:
a = arr * 5

In [42]:
a-1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [43]:
np.eye(3)#Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.eye(3 ,dtype = (int))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [45]:
np.empty((3,4))# Return a new array of given shape and type, without initializing entries.

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [50]:
## optional topic ## random module


import random
random.choice((1,2,3,4,5))

4

In [51]:
random.choice('atul')

'a'

In [52]:
random.randrange(1,10)

5

In [54]:
random.random()## no is generated b/w 0 and 1

0.45803918192615656

In [55]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [56]:
random.shuffle(lis)

In [57]:
lis

[5, 3, 1, 2, 4]

In [58]:
random.uniform(7,14)

8.56956821428194

In [60]:
## to have random numbers related concepts in numpy
np.array([])

array([], dtype=float64)

In [61]:
np.random.random_sample()

0.16610488185481687

In [62]:
np.random.random_sample((5,))

array([0.863429  , 0.1296777 , 0.61780511, 0.23495981, 0.27570842])

In [63]:
np.random.rand(1)

array([0.07322578])

In [64]:
np.random.rand(2,3)

array([[0.82038985, 0.97371963, 0.4062325 ],
       [0.22251442, 0.10829149, 0.75765733]])

In [65]:
np.random.rand(2,3)

array([[0.89241725, 0.32235941, 0.43394512],
       [0.69355483, 0.41278257, 0.3153309 ]])

In [68]:
arr = np.random.randint(1,5,size=(3,4))

In [69]:
arr.shape

(3, 4)

In [70]:
arr.size

12

In [71]:
arr

array([[2, 2, 4, 3],
       [4, 4, 2, 3],
       [1, 4, 2, 1]])

In [74]:
## rehaping the array

arr1 = arr.reshape(2,6)

In [75]:
arr1.shape

(2, 6)

In [76]:
arr1.size

12

In [77]:
arr

array([[2, 2, 4, 3],
       [4, 4, 2, 3],
       [1, 4, 2, 1]])

In [78]:
arr.size

12

In [79]:
## array size will not change , always resape parameter should be multiplication of orginal array size

In [80]:
arr

array([[2, 2, 4, 3],
       [4, 4, 2, 3],
       [1, 4, 2, 1]])

In [81]:
arr.size

12

In [86]:
arr.reshape(2,5) ## multiplication is not 12

ValueError: cannot reshape array of size 12 into shape (2,5)

In [84]:
arr.reshape(1,12)

array([[2, 2, 4, 3, 4, 4, 2, 3, 1, 4, 2, 1]])

In [85]:
arr.reshape(4,3)

array([[2, 2, 4],
       [3, 4, 4],
       [2, 3, 1],
       [4, 2, 1]])

In [87]:
# case when u dont know in shape what should be coloumn count

arr.reshape(4,-1)

array([[2, 2, 4],
       [3, 4, 4],
       [2, 3, 1],
       [4, 2, 1]])

In [88]:
arr.reshape(2,-1)

array([[2, 2, 4, 3, 4, 4],
       [2, 3, 1, 4, 2, 1]])

In [89]:
arr.reshape(2,-100)

array([[2, 2, 4, 3, 4, 4],
       [2, 3, 1, 4, 2, 1]])

In [91]:
arr1 = arr.reshape(-1,3)## you know coloumn count but now row count

In [92]:
arr1.size

12

In [93]:
arr.reshape(12,1)

array([[2],
       [2],
       [4],
       [3],
       [4],
       [4],
       [2],
       [3],
       [1],
       [4],
       [2],
       [1]])

In [94]:
arr.reshape(12,1).base ## to see the orignal array

array([[2, 2, 4, 3],
       [4, 4, 2, 3],
       [1, 4, 2, 1]])

In [100]:
arr.reshape(2,2,3).ndim

3

In [98]:
arr.reshape(1,2,2,3)

array([[[[2, 2, 4],
         [3, 4, 4]],

        [[2, 3, 1],
         [4, 2, 1]]]])

In [99]:
arr.reshape(1,2,2,3).ndim

4

In [103]:
arr.reshape(4,3,1) ## 3 rows 1 coloumn repeated 4 times in the third dimension

array([[[2],
        [2],
        [4]],

       [[3],
        [4],
        [4]],

       [[2],
        [3],
        [1]],

       [[4],
        [2],
        [1]]])

In [104]:
## condition on array
arr1 = np.random.randint(1,10,(5,6))

In [105]:
arr1

array([[8, 3, 2, 6, 2, 7],
       [2, 6, 3, 9, 7, 8],
       [1, 5, 2, 1, 3, 9],
       [8, 4, 9, 7, 3, 2],
       [2, 6, 5, 5, 4, 9]])

In [106]:
arr1.shape

(5, 6)

In [107]:
arr1.ndim

2

In [108]:
arr1.size

30

In [109]:
arr1 > 3

array([[ True, False, False,  True, False,  True],
       [False,  True, False,  True,  True,  True],
       [False,  True, False, False, False,  True],
       [ True,  True,  True,  True, False, False],
       [False,  True,  True,  True,  True,  True]])

In [111]:
arr1[arr1>3]

array([8, 6, 7, 6, 9, 7, 8, 5, 9, 8, 4, 9, 7, 6, 5, 5, 4, 9])

In [112]:
arr1[arr1<3]

array([2, 2, 2, 1, 2, 1, 2, 2])

In [113]:
arr1

array([[8, 3, 2, 6, 2, 7],
       [2, 6, 3, 9, 7, 8],
       [1, 5, 2, 1, 3, 9],
       [8, 4, 9, 7, 3, 2],
       [2, 6, 5, 5, 4, 9]])

In [117]:
## to acces the elementsin the   array
arr1[0]

array([8, 3, 2, 6, 2, 7])

In [115]:
arr1[1]

array([2, 6, 3, 9, 7, 8])

In [116]:
arr1[1][0]

np.int64(2)

In [118]:
arr1

array([[8, 3, 2, 6, 2, 7],
       [2, 6, 3, 9, 7, 8],
       [1, 5, 2, 1, 3, 9],
       [8, 4, 9, 7, 3, 2],
       [2, 6, 5, 5, 4, 9]])

In [121]:
arr1[0:3] ## 0th roe , !st row , 2nd row

array([[8, 3, 2, 6, 2, 7],
       [2, 6, 3, 9, 7, 8],
       [1, 5, 2, 1, 3, 9]])

In [124]:
arr1 [0:3,[0,2]] ## 0 to 2nd row and 0th and 2 nd coloumn

array([[8, 2],
       [2, 3],
       [1, 2]])

In [125]:
## slicing on n=both rows and  column

In [128]:
arr1[0:3,1:3]

array([[3, 2],
       [6, 3],
       [5, 2]])

In [129]:
arr1[0:2,[0,1]]

array([[8, 3],
       [2, 6]])

In [130]:
arr1[0,[1,3]]

array([3, 6])

In [131]:
arr1[2:4,[0,3]]

array([[1, 1],
       [8, 7]])

In [133]:
arr1[2:5,0:2]

array([[1, 5],
       [8, 4],
       [2, 6]])

In [138]:
## mathematical operation on 2 operations
arr1  = np.random.randint(1,2,(3,3))
arr2 = np.random.randint(1,2,(3,3))

In [135]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [136]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [140]:
arr1+arr2 ## index wise elemet add

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [139]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [142]:
arr1*arr2 ## index multiplication

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [143]:
arr1,arr2

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]))

In [146]:
arr1 /arr2 ## index wise divivsion

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [152]:
arr1/0 ## in pythn 0 diviion error will come , but num py no error

<ipython-input-152-ca90df88797e>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 ## in pythn 0 diviion error will come , but num py no error


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [147]:
## matix multiplication >> different from index multiplication


arr1 @ arr2 ## 1st way to do matrix multiplication

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [150]:
np.dot(arr1,arr2) # 2nd way to do matrix multiplication

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [153]:
arr = np.zeros((3,4))

In [157]:
## boradcasting
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [158]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [159]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [160]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [161]:
a = np.array([1,2,3,4])

In [162]:
a

array([1, 2, 3, 4])

In [163]:
a.ndim

1

In [164]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [169]:
a = np.array([[1,2,3,4]])

In [166]:
a

array([1, 2, 3, 4])

In [170]:
## transpose
a.T

array([[1],
       [2],
       [3],
       [4]])

In [172]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [173]:
arr1.T

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [174]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [175]:
np.sqrt(arr1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [176]:
np.log10(arr1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [177]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [178]:
np.min(arr1)

np.int64(1)

In [179]:
np.max(arr1)

np.int64(1)