<a href="https://colab.research.google.com/github/atulpatil2228/pwlectures/blob/main/Numpy_advance2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [3]:
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [4]:
arr2

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [5]:
arr1.flatten()#Return a copy of the array collapsed into one dimension.


array([1, 1, 1, 1, 1, 2, 2, 1, 2])

In [6]:
## Expading the dimension
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
arr.ndim

1

In [14]:
np.expand_dims(arr,axis=0)## increases the dimension by 1 at provided axis

array([[1, 2, 3, 4]])

In [10]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
np.expand_dims(arr,axis=1).ndim

2

In [11]:
arr

array([1, 2, 3, 4])

In [15]:
arr = np.zeros((3,4))

In [17]:
arr.ndim

2

In [18]:
np.expand_dims(arr,axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [20]:
np.expand_dims(arr,axis=1).ndim

3

In [21]:
a = np.array([[1],[2],[3]])

In [22]:
a.ndim

2

In [24]:
np.squeeze(a)## Remove axes of length from "a"

array([1, 2, 3])

In [25]:
a

array([[1],
       [2],
       [3]])

In [26]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [27]:
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [28]:
np.repeat(arr1,2)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2])

In [29]:
np.repeat(arr1,2,axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 2],
       [1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [30]:
np.repeat(arr1,3,axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 2],
       [1, 1, 2],
       [1, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [31]:
np.repeat(arr1,3,axis=1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 2, 2, 2],
       [2, 2, 2, 1, 1, 1, 2, 2, 2]])

In [32]:
a

array([[1],
       [2],
       [3]])

In [34]:
np.roll(a,-1)

array([[2],
       [3],
       [1]])

In [35]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [36]:
c= np.array([[1,2],[3,4],[5,6],[7,8]])

In [37]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
np.roll(c,-2)

array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [39]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [40]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [41]:
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [42]:
arr2

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [43]:
arr1+arr2

array([[3, 3, 2],
       [3, 3, 4],
       [4, 2, 4]])

In [44]:
arr1-arr2

array([[-1, -1,  0],
       [-1, -1,  0],
       [ 0,  0,  0]])

In [45]:
arr1 * arr2

array([[2, 2, 1],
       [2, 2, 4],
       [4, 1, 4]])

In [46]:
arr1 >arr2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [47]:
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [48]:
~arr1

array([[-2, -2, -2],
       [-2, -2, -3],
       [-3, -2, -3]])

In [49]:
## operation on numpy on string array

In [50]:
d = np.array(['pw','skills'])

In [51]:
d

array(['pw', 'skills'], dtype='<U6')

In [52]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [53]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [54]:
## Mathematical functions

In [55]:
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [56]:
np.sin(arr1)

array([[0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.90929743],
       [0.90929743, 0.84147098, 0.90929743]])

In [57]:
np.cos(arr1)

array([[ 0.54030231,  0.54030231,  0.54030231],
       [ 0.54030231,  0.54030231, -0.41614684],
       [-0.41614684,  0.54030231, -0.41614684]])

In [58]:
np.tan(arr1)

array([[ 1.55740772,  1.55740772,  1.55740772],
       [ 1.55740772,  1.55740772, -2.18503986],
       [-2.18503986,  1.55740772, -2.18503986]])

In [59]:
np.log10(arr1)

array([[0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.30103],
       [0.30103, 0.     , 0.30103]])

In [60]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [61]:
np.power(arr1,3)

array([[1, 1, 1],
       [1, 1, 8],
       [8, 1, 8]])

In [62]:
np.mean(arr1)

np.float64(1.3333333333333333)

In [63]:
np.max(arr1)

np.int64(2)

In [64]:
np.mean(arr1)

np.float64(1.3333333333333333)

In [65]:
np.std(arr1)

np.float64(0.4714045207910317)

In [66]:
np.var(arr1)

np.float64(0.2222222222222222)

In [67]:
arr1-arr2

array([[-1, -1,  0],
       [-1, -1,  0],
       [ 0,  0,  0]])

In [68]:
np.subtract(arr1,arr2)

array([[-1, -1,  0],
       [-1, -1,  0],
       [ 0,  0,  0]])

In [69]:
arr1*arr2

array([[2, 2, 1],
       [2, 2, 4],
       [4, 1, 4]])

In [70]:
np.multiply(arr1,arr2)

array([[2, 2, 1],
       [2, 2, 4],
       [4, 1, 4]])

In [72]:
np.mod(arr1,arr2)## return element wise remainder

array([[1, 1, 0],
       [1, 1, 0],
       [0, 0, 0]])

In [73]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356]])

In [74]:
# sort search

e = np.array([5,6,1,2])

In [75]:
e

array([5, 6, 1, 2])

In [76]:
np.sort(e)

array([1, 2, 5, 6])

In [77]:
f = np.array([5,199,6,7,8])

In [78]:
f

array([  5, 199,   6,   7,   8])

In [79]:
np.sort(f)

array([  5,   6,   7,   8, 199])

In [80]:
np.searchsorted(f,170)#Find indices where elements should be inserted to maintain order

np.int64(5)

In [81]:
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [82]:
f = np.array([5,199,200,6,7,0,0,0,8])

In [83]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [84]:
np.count_nonzero(f)

6

In [86]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [88]:
np.where (f>0)

(array([0, 1, 2, 3, 4, 8]),)

In [89]:
np.extract(f>0,f)

array([  5, 199, 200,   6,   7,   8])

In [90]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [91]:
f.byteswap()

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         432345564227567616,   504403158265495552,                    0,
                          0,                    0,   576460752303423488])

In [92]:
## matrix >> 2d array

import numpy.matlib as nm

In [93]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [95]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
## numpy >> liner algebra

arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,4))

In [103]:
arr1

array([[3, 6, 8],
       [7, 2, 9],
       [6, 7, 6]])

In [104]:
arr2

array([[3, 7, 4, 4],
       [5, 1, 6, 4],
       [8, 9, 9, 1]])

In [105]:
arr1@ arr2

array([[103,  99, 120,  44],
       [103, 132, 121,  45],
       [101, 103, 120,  58]])

In [106]:
arr1

array([[3, 6, 8],
       [7, 2, 9],
       [6, 7, 6]])

In [107]:
np.linalg.det(arr1)

np.float64(214.99999999999991)

In [108]:
np.linalg.inv(arr1)

array([[-0.2372093 ,  0.09302326,  0.17674419],
       [ 0.05581395, -0.13953488,  0.13488372],
       [ 0.17209302,  0.06976744, -0.16744186]])

In [110]:
a = np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [112]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [113]:
b = np.array([16,-8,0])

In [114]:
b

array([16, -8,  0])

In [115]:
np.linalg.solve(a,b)

array([0.90162081, 2.89483603, 1.88465888])